const app=document.querySelector('#app');
const STORE='kart-license-quiz-v1';
const COURSE_STORE='kart-license-course-v1';
let db=null,courseDb=null;
let state={view:'home',chapter:null,mode:null,current:null,answerOrder:[],selected:new Set(),checked:false,exam:null,course:null};
const loadStats=()=>{try{return JSON.parse(localStorage.getItem(STORE))||{questions:{},sessions:0}}catch{return{questions:{},sessions:0}}};
const loadCourseStats=()=>{try{return JSON.parse(localStorage.getItem(COURSE_STORE))||{lessons:{}}}catch{return{lessons:{}}}};
let stats=loadStats(),courseStats=loadCourseStats();
const saveStats=()=>localStorage.setItem(STORE,JSON.stringify(stats));
const saveCourseStats=()=>localStorage.setItem(COURSE_STORE,JSON.stringify(courseStats));
const shuffle=a=>{const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x};
const qStat=id=>stats.questions[id]||{seen:0,right:0,wrong:0,streak:0,last:0};
const weight=q=>{const s=qStat(q.id);if(!s.seen)return 4;if(s.wrong>s.right)return 4;if(s.streak>=4)return 1;if(s.wrong>0)return 2;return 1};
const sameSet=(a,b)=>a.length===b.length&&a.every(v=>b.includes(v));
function weightedPick(pool){const expanded=[];pool.forEach(q=>{for(let i=0;i<weight(q);i++)expanded.push(q)});return expanded[Math.floor(Math.random()*expanded.length)]}
function screen(html){app.innerHTML=html;window.scrollTo({top:0,behavior:'smooth'})}
function versionInfoHtml(){const m=db.meta;return `<details class="version-info"><summary>Kart-Lizenz-Quiz v${m.appVersion} · Quiz-Daten v${m.dataVersion}</summary><div class="version-details"><p><strong>App:</strong> v${m.appVersion}</p><p><strong>Kurs:</strong> v${m.courseVersion||'—'}</p><p><strong>Fragen · Antworten · Erklärungen:</strong> v${m.dataVersion} · Stand ${formatDate(m.dataUpdated)}</p><p><strong>DMSB-Quellkatalog:</strong> ${m.catalogStand} · ${m.questionCount} Fragen</p><p><strong>Fachlicher Status:</strong> ${m.solutionStatusLabel}</p></div></details>`}
function formatDate(iso){if(!iso)return '—';const [y,m,d]=iso.split('-');return `${d}.${m}.${y}`}
function home(){state.view='home';screen(`<section class="card hero"><div class="kart">🏎️</div><h1>Kart-Lizenz-Trainer</h1><p>Den Stoff verstehen, Fragen üben und sicherer für den Lizenzlehrgang werden.</p></section><section class="card"><div class="menu two"><button class="btn course-btn" id="course">📖 Kurs</button><button class="btn" id="learn">📚 Fragen lernen</button><button class="btn" id="exam">🏁 Prüfung üben</button><button class="btn secondary" id="stats">⭐ Mein Lernstand</button><button class="btn secondary" id="hard">🔁 Schwierige Fragen</button></div></section><section class="card course-teaser"><h2>Neu: Nicht nur auswendig lernen 💡</h2><p>Im Kurs liest du kurze Lektionen, beantwortest Verständnisfragen und übst danach die passenden echten DMSB-Fragen.</p><p class="subtle">Pilot: Kapitel 4 · Auf der Rennstrecke · 7 kurze Lektionen</p></section><section class="card"><p><strong>${db.questions.length} DMSB-Fragen</strong> sind mit einem derzeit noch geprüften Lösungs- und Erklärungsstand hinterlegt.</p><div class="notice">Der DMSB veröffentlicht keine Lösungsschablone. Unsere Lösungen und Erklärungen werden deshalb einzeln gegen die Regelwerke geprüft.</div></section><div class="footer">${versionInfoHtml()}<p>Lernstand wird nur auf diesem Gerät im Browser gespeichert.</p></div>`);
document.querySelector('#course').onclick=courseHome;document.querySelector('#learn').onclick=chapterSelect;document.querySelector('#exam').onclick=examSetup;document.querySelector('#stats').onclick=statsView;document.querySelector('#hard').onclick=()=>startLearn('hard')}
function courseHome(){const all=courseDb.chapters;const total=all.reduce((n,c)=>n+c.lessons.length,0);const done=all.reduce((n,c)=>n+c.lessons.filter(l=>courseStats.lessons[l.id]?.completed).length,0);screen(`<section class="card hero course-hero"><div class="kart">📖</div><h1>Kart-Lizenz-Kurs</h1><p>Kurze Lektionen lesen, verstehen und danach die echten DMSB-Fragen üben.</p><div class="progress"><span style="width:${total?done/total*100:0}%"></span></div><p class="subtle">${done} von ${total} Lektionen abgeschlossen</p></section><section class="card"><div class="lesson-list">${all.map(ch=>{const cd=ch.lessons.filter(l=>courseStats.lessons[l.id]?.completed).length;const unlocked=cd===ch.lessons.length;return `<button class="lesson-card" data-chapter="${ch.id}"><span class="lesson-emoji">${unlocked?'🏁':'📘'}</span><span><strong>Kapitel ${ch.id}: ${ch.title}</strong><small>${ch.subtitle} · ${cd}/${ch.lessons.length} Lektionen</small></span><span class="lesson-state">${unlocked?'✅':'›'}</span></button>`}).join('')}</div><div class="actions"><button class="btn ghost" id="back">← Startseite</button></div></section>`);document.querySelectorAll('[data-chapter]').forEach(b=>b.onclick=()=>courseChapter(b.dataset.chapter));document.querySelector('#back').onclick=home}
function chapterById(id){return courseDb.chapters.find(c=>String(c.id)===String(id))}
function courseChapter(id){const ch=chapterById(id),done=ch.lessons.filter(l=>courseStats.lessons[l.id]?.completed).length,unlocked=done===ch.lessons.length;const qids=[...new Set(ch.lessons.flatMap(l=>l.dmsbQuestions))];screen(`<section class="card hero course-hero"><span class="pill">Kapitel ${ch.id}</span><h1>${ch.title}</h1><p>${ch.subtitle}</p><div class="progress"><span style="width:${done/ch.lessons.length*100}%"></span></div><p class="subtle">${done} von ${ch.lessons.length} Lektionen abgeschlossen</p></section><section class="card"><div class="lesson-list">${ch.lessons.map((l,i)=>{const s=courseStats.lessons[l.id];return `<button class="lesson-card" data-lesson="${l.id}"><span class="lesson-emoji">${l.emoji}</span><span><strong>${i+1}. ${l.title}</strong><small>ca. ${l.minutes} Minuten · ${l.questions.length} Verständnisfragen</small></span><span class="lesson-state">${s?.completed?'✅':'›'}</span></button>`}).join('')}</div></section><section class="card ${unlocked?'course-teaser':'locked-course'}"><h2>${unlocked?'🏁 Kapitel geschafft!':'🔒 DMSB-Fragen – Kapitel '+ch.id}</h2><p>${unlocked?`Jetzt kannst du die ${qids.length} passenden Originalfragen aus dem DMSB-Fragenkatalog üben.`:`Schließe zuerst alle ${ch.lessons.length} Lerneinheiten dieses Kapitels ab. Danach werden die passenden DMSB-Fragen freigeschaltet.`}</p>${unlocked?'<button class="btn course-btn" id="chapterPractice">🏎️ DMSB-Fragen üben</button>':''}<div class="actions"><button class="btn ghost" id="back">← Kursübersicht</button></div></section>`);document.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>openLesson(b.dataset.lesson));if(unlocked)document.querySelector('#chapterPractice').onclick=()=>startLearnIds(qids);document.querySelector('#back').onclick=courseHome}
function lessonById(id){return courseDb.chapters.flatMap(c=>c.lessons).find(l=>l.id===id)}
function chapterForLesson(id){return courseDb.chapters.find(c=>c.lessons.some(l=>l.id===id))}
function openLesson(id){const l=lessonById(id);state.course={lesson:l,step:'read',cq:0,selected:null,answers:[],score:0};renderLesson()}
function renderLesson(){const c=state.course,l=c.lesson,ch=chapterForLesson(l.id);if(c.step==='read'){screen(`<section class="card lesson"><div class="topbar"><span class="pill">${l.emoji} Lektion ${l.id}</span><span class="subtle">ca. ${l.minutes} Min.</span></div><h1>${l.title}</h1><p class="lesson-intro">${l.intro}</p>${l.sections.map(s=>`<section class="lesson-section"><h2>${s.heading}</h2><p>${s.text}</p></section>`).join('')}<div class="remember"><strong>🧠 Merke dir</strong><p>${l.remember}</p></div>${l.sources?.length?`<details class="course-source"><summary>📖 Regelquelle</summary><p>${l.sources.map(s=>`${s.document} · ${s.section}`).join('<br>')}</p></details>`:''}<div class="actions"><button class="btn course-btn" id="understand">Verstanden – Fragen starten →</button><button class="btn ghost" id="back">← Kapitelübersicht</button></div></section>`);document.querySelector('#understand').onclick=()=>{c.step='quiz';c.cq=0;c.score=0;c.answers=[];renderLesson()};document.querySelector('#back').onclick=()=>courseChapter(ch.id);return}if(c.step==='quiz'){const q=l.questions[c.cq],answered=c.answers[c.cq];screen(`<section class="card"><div class="topbar"><span class="pill">${l.emoji} ${l.title}</span><span class="subtle">Verständnis ${c.cq+1}/${l.questions.length}</span></div><div class="progress"><span style="width:${(c.cq+1)/l.questions.length*100}%"></span></div><div class="question">${q.q}</div><div class="answers">${q.answers.map((a,i)=>{let cls='answer';if(answered){if(q.correct.includes(i))cls+=' correct';if(answered.selected===i&&!q.correct.includes(i))cls+=' wrong'}return `<label class="${cls}"><input type="radio" name="cq" data-cq="${i}" ${answered?'disabled':''}><span>${a}</span></label>`}).join('')}</div>${answered?`<div class="feedback ${answered.ok?'good':'bad'}">${answered.ok?'✅ Genau!':'🙂 Noch nicht ganz.'}<p>${q.explain}</p></div>`:''}<div class="actions">${answered?`<button class="btn course-btn" id="nextc">${c.cq===l.questions.length-1?'Auswertung →':'Nächste Frage →'}</button>`:'<button class="btn course-btn" id="checkc" disabled>Antwort prüfen</button>'}<button class="btn ghost" id="back">Lektion verlassen</button></div></section>`);if(!answered){document.querySelectorAll('[data-cq]').forEach(e=>e.onchange=()=>{c.selected=Number(e.dataset.cq);document.querySelector('#checkc').disabled=false});document.querySelector('#checkc').onclick=()=>{const ok=q.correct.includes(c.selected);c.answers[c.cq]={selected:c.selected,ok};if(ok)c.score++;renderLesson()}}else document.querySelector('#nextc').onclick=()=>{if(c.cq===l.questions.length-1){c.step='done';finishLesson()}else{c.cq++;c.selected=null;renderLesson()}};document.querySelector('#back').onclick=()=>courseChapter(ch.id);return}}
function finishLesson(){const c=state.course,l=c.lesson,ch=chapterForLesson(l.id);courseStats.lessons[l.id]={completed:true,score:c.score,total:l.questions.length,last:Date.now()};saveCourseStats();const pct=Math.round(c.score/l.questions.length*100),idx=ch.lessons.findIndex(x=>x.id===l.id),next=ch.lessons[idx+1],chapterDone=ch.lessons.every(x=>courseStats.lessons[x.id]?.completed);screen(`<section class="card hero"><div class="kart">${pct===100?'🌟':'🏁'}</div><h1>Lektion geschafft!</h1><p><strong>${c.score} von ${l.questions.length}</strong> Verständnisfragen richtig.</p><p>${chapterDone?'Damit ist dieses Kapitel vollständig bearbeitet.':next?'Weiter geht es mit der nächsten Lerneinheit.':'Zur Kapitelübersicht.'}</p></section><section class="card"><div class="actions">${next?`<button class="btn course-btn" id="nextLesson">Nächste Lektion: ${next.title} →</button>`:''}${chapterDone?'<button class="btn course-btn" id="chapterDone">🏁 Kapitelabschluss & DMSB-Fragen</button>':''}<button class="btn secondary" id="again">Lektion noch einmal</button><button class="btn ghost" id="chapterhome">Kapitelübersicht</button></div></section>`);if(next)document.querySelector('#nextLesson').onclick=()=>openLesson(next.id);if(chapterDone)document.querySelector('#chapterDone').onclick=()=>courseChapter(ch.id);document.querySelector('#again').onclick=()=>openLesson(l.id);document.querySelector('#chapterhome').onclick=()=>courseChapter(ch.id)}
function chapterSelect(){screen(`<section class="card"><h2>Was möchtest du lernen?</h2><div class="chapter-grid"><button class="chapter" data-ch="all"><strong>🎯 Alles lernen</strong>Alle Kapitel mischen</button>${Object.entries(db.chapters).map(([n,name])=>`<button class="chapter" data-ch="${n}"><strong>Kapitel ${n}</strong>${name}</button>`).join('')}</div><div class="actions"><button class="btn ghost" id="back">← Zurück</button></div></section>`);document.querySelectorAll('[data-ch]').forEach(b=>b.onclick=()=>startLearn(b.dataset.ch));document.querySelector('#back').onclick=home}
function poolFor(ch){if(Array.isArray(ch))return db.questions.filter(q=>ch.includes(q.id));if(ch==='hard')return db.questions.filter(q=>{const s=qStat(q.id);return s.wrong>0&&s.wrong>=s.right/2});if(ch==='all')return db.questions;return db.questions.filter(q=>String(q.chapter)===String(ch))}
function startLearnIds(ids){state.mode='learn';state.chapter=[...ids];nextLearn()}
function startLearn(ch){const pool=poolFor(ch);if(!pool.length){screen(`<section class="card"><h2>Noch keine schwierigen Fragen 🎉</h2><p>Wenn du später Fragen falsch beantwortest, erscheinen sie hier automatisch.</p><button class="btn" id="back">Zurück</button></section>`);document.querySelector('#back').onclick=home;return}state.mode='learn';state.chapter=ch;nextLearn()}
function nextLearn(){const pool=poolFor(state.chapter);state.current=weightedPick(pool);state.answerOrder=shuffle(state.current.answers.map((_,i)=>i));state.selected=new Set();state.checked=false;renderQuestion()}
function renderQuestion(){const q=state.current;const s=qStat(q.id);screen(`<section class="card"><div class="topbar"><span class="pill">Kapitel ${q.chapter}</span><span class="subtle">Frage ${q.id}</span></div><div class="question">${q.question}</div><p class="subtle">Es können eine oder mehrere Antworten richtig sein.</p><div class="answers">${state.answerOrder.map(i=>{const a=q.answers[i];let cls='answer';if(state.selected.has(i))cls+=' selected';if(state.checked&&a.correct)cls+=' correct';if(state.checked&&state.selected.has(i)&&!a.correct)cls+=' wrong';return `<label class="${cls}"><input type="checkbox" data-a="${i}" ${state.selected.has(i)?'checked':''} ${state.checked?'disabled':''}><span>${a.text}</span></label>`}).join('')}</div>${state.checked?feedbackHtml(q):''}<div class="actions">${state.checked?'<button class="btn" id="next">Nächste Frage →</button>':'<button class="btn" id="check">Antwort prüfen</button>'}<button class="btn ghost" id="home">Beenden</button></div>${s.seen?`<p class="subtle">Diese Frage: ${s.right}× richtig · ${s.wrong}× noch nicht richtig</p>`:''}</section>`);document.querySelectorAll('[data-a]').forEach(el=>el.onchange=e=>{const i=Number(e.target.dataset.a);e.target.checked?state.selected.add(i):state.selected.delete(i);renderQuestion()});document.querySelector('#home').onclick=home;if(state.checked)document.querySelector('#next').onclick=nextLearn;else document.querySelector('#check').onclick=checkLearn}
function tipHtml(q){if(!q.quickTip&&!q.sources?.length)return '';return `<div class="quicktip"><h3>💡 QuickTipp</h3>${q.quickTip?`<p>${q.quickTip}</p>`:''}${q.sources?.length?`<p class="source">📖 Nachlesen: ${q.sources.map(x=>`${x.document}${x.section?' · '+x.section:''}`).join(' · ')}</p>`:''}</div>`}
function feedbackHtml(q){const correct=q.answers.map((a,i)=>a.correct?i:null).filter(i=>i!==null);const ok=sameSet([...state.selected],correct);return `<div class="feedback ${ok?'good':'bad'}">${ok?'✅ Richtig!':'🙂 Noch nicht ganz. Die richtigen Antworten sind grün markiert.'}</div>${tipHtml(q)}`}
function checkLearn(){const q=state.current;const correct=q.answers.map((a,i)=>a.correct?i:null).filter(i=>i!==null);const ok=sameSet([...state.selected],correct);const s=qStat(q.id);s.seen++;s.last=Date.now();if(ok){s.right++;s.streak++}else{s.wrong++;s.streak=0}stats.questions[q.id]=s;saveStats();state.checked=true;renderQuestion()}
function examSetup(){screen(`<section class="card exam-setup"><h2>🏁 Prüfung üben</h2><p>Während der Prüfung gibt es keine Auflösung. Erst am Ende siehst du dein Ergebnis.</p><label for="count">Wie viele Fragen?</label><select id="count">${[10,20,30].filter(n=>n<=db.questions.length).map(n=>`<option>${n}</option>`).join('')}</select><label for="mins">Wie viele Minuten?</label><select id="mins"><option>10</option><option selected>20</option><option>30</option></select><div class="actions"><button class="btn" id="real">🏁 Prüfungssimulation · 30 Fragen · 30 Minuten</button><button class="btn secondary" id="start">Eigene Prüfung starten</button><button class="btn ghost" id="back">Zurück</button></div></section>`);document.querySelector('#back').onclick=home;document.querySelector('#real').onclick=()=>startExam(30,30);document.querySelector('#start').onclick=()=>startExam(Number(document.querySelector('#count').value),Number(document.querySelector('#mins').value))}
function startExam(count,mins){state.exam={questions:shuffle(db.questions).slice(0,count),index:0,answers:{},end:Date.now()+mins*60000,timer:null};state.mode='exam';examQuestion();state.exam.timer=setInterval(()=>{if(!state.exam)return;const left=state.exam.end-Date.now();if(left<=0){clearInterval(state.exam.timer);finishExam();return}const e=document.querySelector('#timer');if(e){e.textContent=formatTime(left);if(left<120000)e.classList.add('warn')}},1000)}
function formatTime(ms){const s=Math.max(0,Math.ceil(ms/1000));return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}
function examQuestion(){const ex=state.exam,q=ex.questions[ex.index];state.current=q;const selected=new Set(ex.answers[q.id]||[]);const order=shuffle(q.answers.map((_,i)=>i));screen(`<section class="card"><div class="topbar"><span class="pill">Frage ${ex.index+1} von ${ex.questions.length}</span><span class="pill timer" id="timer">${formatTime(ex.end-Date.now())}</span></div><div class="progress"><span style="width:${((ex.index+1)/ex.questions.length)*100}%"></span></div><div class="question">${q.question}</div><p class="subtle">Eine oder mehrere Antworten können richtig sein.</p><div class="answers">${order.map(i=>`<label class="answer"><input type="checkbox" data-a="${i}" ${selected.has(i)?'checked':''}><span>${q.answers[i].text}</span></label>`).join('')}</div><div class="actions"><button class="btn" id="next">${ex.index===ex.questions.length-1?'Prüfung abgeben':'Weiter →'}</button>${ex.index>0?'<button class="btn secondary" id="prev">← Zurück</button>':''}</div></section>`);document.querySelectorAll('[data-a]').forEach(el=>el.onchange=()=>{const vals=[...document.querySelectorAll('[data-a]:checked')].map(x=>Number(x.dataset.a));ex.answers[q.id]=vals});document.querySelector('#next').onclick=()=>{if(ex.index===ex.questions.length-1)finishExam();else{ex.index++;examQuestion()}};const p=document.querySelector('#prev');if(p)p.onclick=()=>{ex.index--;examQuestion()}}
function finishExam(){const ex=state.exam;if(!ex)return;clearInterval(ex.timer);let right=0;const rows=ex.questions.map(q=>{const chosen=ex.answers[q.id]||[];const correct=q.answers.map((a,i)=>a.correct?i:null).filter(i=>i!==null);const ok=sameSet(chosen,correct);if(ok)right++;return{q,ok,chosen,correct}});state.exam=null;const pct=Math.round(right/rows.length*100);screen(`<section class="card hero"><div class="kart">${pct>=80?'🏆':'🏁'}</div><h2>Prüfung beendet</h2><div class="stats"><div class="stat"><strong>${right}/${rows.length}</strong>richtig</div><div class="stat"><strong>${pct}%</strong>Ergebnis</div></div></section><section class="card"><h3>Noch einmal anschauen</h3>${rows.filter(r=>!r.ok).length?rows.filter(r=>!r.ok).map(r=>`<div class="exam-review"><p><strong>${r.q.id}</strong> ${r.q.question}</p><p><strong>Richtig:</strong> ${r.correct.map(i=>r.q.answers[i].text).join(' · ')}</p>${tipHtml(r.q)}</div>`).join(''):'<p>Alle Fragen richtig – stark! 🎉</p>'}<div class="actions"><button class="btn" id="again">Neue Prüfung</button><button class="btn ghost" id="home">Startseite</button></div></section>`);document.querySelector('#again').onclick=examSetup;document.querySelector('#home').onclick=home}
function statsView(){const entries=db.questions.map(q=>({q,s:qStat(q.id)}));const seen=entries.filter(x=>x.s.seen>0);const right=seen.reduce((n,x)=>n+x.s.right,0),wrong=seen.reduce((n,x)=>n+x.s.wrong,0),attempts=right+wrong,pct=attempts?Math.round(right/attempts*100):0;const hard=entries.filter(x=>x.s.wrong>0).sort((a,b)=>(b.s.wrong-b.s.right)-(a.s.wrong-a.s.right)).slice(0,8);const lessons=courseDb.chapters.flatMap(c=>c.lessons);const done=lessons.filter(l=>courseStats.lessons[l.id]?.completed).length;screen(`<section class="card"><h2>⭐ Mein Lernstand</h2><div class="stats"><div class="stat"><strong>${done}/${lessons.length}</strong>Kurslektionen</div><div class="stat"><strong>${seen.length}</strong>Fragen gesehen</div><div class="stat"><strong>${right}</strong>richtig</div><div class="stat"><strong>${pct}%</strong>Trefferquote</div></div></section><section class="card"><h3>Das üben wir noch</h3>${hard.length?hard.map(x=>`<p><strong>${x.q.id}</strong> ${x.q.question}</p>`).join(''):'<p>Noch keine schwierigen Fragen gespeichert.</p>'}<div class="actions"><button class="btn course-btn" id="course">📖 Zum Kurs</button><button class="btn" id="hard">Schwierige Fragen üben</button><button class="btn ghost" id="reset">Lernstand zurücksetzen</button><button class="btn secondary" id="back">Zurück</button></div></section>`);document.querySelector('#course').onclick=courseHome;document.querySelector('#hard').onclick=()=>startLearn('hard');document.querySelector('#back').onclick=home;document.querySelector('#reset').onclick=()=>{if(confirm('Quiz- und Kurs-Lernstand wirklich zurücksetzen?')){stats={questions:{},sessions:0};courseStats={lessons:{}};saveStats();saveCourseStats();statsView()}}}
async function init(){try{const [qr,cr]=await Promise.all([fetch('data/questions.json?v=0.6',{cache:'no-store'}),fetch('data/course.json?v=0.6',{cache:'no-store'})]);if(!qr.ok||!cr.ok)throw new Error('Lerndaten konnten nicht geladen werden');db=await qr.json();courseDb=await cr.json();home()}catch(err){screen(`<section class="card"><h2>Die Lerndaten konnten nicht geladen werden.</h2><p>${err.message}</p><p class="subtle">Starte die Seite über einen kleinen Webserver oder über GitHub Pages – nicht direkt als file://-Datei.</p></section>`)}}
init();
