const app=document.querySelector('#app');
const STORE='kart-license-quiz-v1';
let db=null;
let state={view:'home',chapter:null,mode:null,current:null,answerOrder:[],selected:new Set(),checked:false,exam:null};
const loadStats=()=>{try{return JSON.parse(localStorage.getItem(STORE))||{questions:{},sessions:0}}catch{return{questions:{},sessions:0}}};
let stats=loadStats();
const saveStats=()=>localStorage.setItem(STORE,JSON.stringify(stats));
const shuffle=a=>{const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x};
const qStat=id=>stats.questions[id]||{seen:0,right:0,wrong:0,streak:0,last:0};
const weight=q=>{const s=qStat(q.id);if(!s.seen)return 4;if(s.wrong>s.right)return 4;if(s.streak>=4)return 1;if(s.wrong>0)return 2;return 1};
const sameSet=(a,b)=>a.length===b.length&&a.every(v=>b.includes(v));
function weightedPick(pool){const expanded=[];pool.forEach(q=>{for(let i=0;i<weight(q);i++)expanded.push(q)});return expanded[Math.floor(Math.random()*expanded.length)]}
function screen(html){app.innerHTML=html;window.scrollTo({top:0,behavior:'smooth'})}
function versionInfoHtml(){const m=db.meta;return `<details class="version-info"><summary>Kart-Lizenz-Quiz v${m.appVersion} · Quiz-Daten v${m.dataVersion}</summary><div class="version-details"><p><strong>App:</strong> v${m.appVersion}</p><p><strong>Fragen · Antworten · Erklärungen:</strong> v${m.dataVersion} · Stand ${formatDate(m.dataUpdated)}</p><p><strong>DMSB-Quellkatalog:</strong> ${m.catalogStand} · ${m.questionCount} Fragen</p><p><strong>Fachlicher Status:</strong> ${m.solutionStatusLabel}</p></div></details>`}
function formatDate(iso){if(!iso)return '—';const [y,m,d]=iso.split('-');return `${d}.${m}.${y}`}
function home(){state.view='home';screen(`<section class="card hero"><div class="kart">🏎️</div><h1>Kart-Lizenz-Quiz</h1><p>Fragen üben, sicherer werden und die schwierigen Fragen öfter wiederholen.</p></section><section class="card"><div class="menu two"><button class="btn" id="learn">📚 Lernen</button><button class="btn" id="exam">🏁 Prüfung üben</button><button class="btn secondary" id="stats">⭐ Mein Lernstand</button><button class="btn secondary" id="hard">🔁 Schwierige Fragen</button></div></section><section class="card"><p><strong>${db.questions.length} Fragen</strong> sind mit einem derzeit noch geprüften Lösungs- und Erklärungsstand hinterlegt.</p><p class="subtle">DMSB-Fragenkatalog: Stand ${db.meta.catalogStand}; zugrunde liegende Reglements: ${db.meta.regulations}.</p><div class="notice">Wichtig: Der DMSB veröffentlicht keine Lösungsschablone. Unsere Lösungen und Erklärungen werden deshalb einzeln gegen die Regelwerke geprüft.</div></section><div class="footer">${versionInfoHtml()}<p>Lernstand wird nur auf diesem Gerät im Browser gespeichert.</p></div>`);document.querySelector('#learn').onclick=chapterSelect;document.querySelector('#exam').onclick=examSetup;document.querySelector('#stats').onclick=statsView;document.querySelector('#hard').onclick=()=>startLearn('hard')}
function chapterSelect(){screen(`<section class="card"><h2>Was möchtest du lernen?</h2><div class="chapter-grid"><button class="chapter" data-ch="all"><strong>🎯 Alles lernen</strong>Alle Kapitel mischen</button>${Object.entries(db.chapters).map(([n,name])=>`<button class="chapter" data-ch="${n}"><strong>Kapitel ${n}</strong>${name}</button>`).join('')}</div><div class="actions"><button class="btn ghost" id="back">← Zurück</button></div></section>`);document.querySelectorAll('[data-ch]').forEach(b=>b.onclick=()=>startLearn(b.dataset.ch));document.querySelector('#back').onclick=home}
function poolFor(ch){if(ch==='hard')return db.questions.filter(q=>{const s=qStat(q.id);return s.wrong>0&&s.wrong>=s.right/2});if(ch==='all')return db.questions;return db.questions.filter(q=>String(q.chapter)===String(ch))}
function startLearn(ch){const pool=poolFor(ch);if(!pool.length){screen(`<section class="card"><h2>Noch keine schwierigen Fragen 🎉</h2><p>Wenn du später Fragen falsch beantwortest, erscheinen sie hier automatisch.</p><button class="btn" id="back">Zurück</button></section>`);document.querySelector('#back').onclick=home;return}state.mode='learn';state.chapter=ch;nextLearn()}
function nextLearn(){const pool=poolFor(state.chapter);state.current=weightedPick(pool);state.answerOrder=shuffle(state.current.answers.map((_,i)=>i));state.selected=new Set();state.checked=false;renderQuestion()}
function renderQuestion(){const q=state.current;const s=qStat(q.id);screen(`<section class="card"><div class="topbar"><span class="pill">Kapitel ${q.chapter}</span><span class="subtle">Frage ${q.id}</span></div><div class="question">${q.question}</div><p class="subtle">Es können eine oder mehrere Antworten richtig sein.</p><div class="answers">${state.answerOrder.map(i=>{const a=q.answers[i];let cls='answer';if(state.selected.has(i))cls+=' selected';if(state.checked&&a.correct)cls+=' correct';if(state.checked&&state.selected.has(i)&&!a.correct)cls+=' wrong';return `<label class="${cls}"><input type="checkbox" data-a="${i}" ${state.selected.has(i)?'checked':''} ${state.checked?'disabled':''}><span>${a.text}</span></label>`}).join('')}</div>${state.checked?feedbackHtml(q):''}<div class="actions">${state.checked?'<button class="btn" id="next">Nächste Frage →</button>':'<button class="btn" id="check">Antwort prüfen</button>'}<button class="btn ghost" id="home">Beenden</button></div>${s.seen?`<p class="subtle">Diese Frage: ${s.right}× richtig · ${s.wrong}× noch nicht richtig</p>`:''}</section>`);document.querySelectorAll('[data-a]').forEach(el=>el.onchange=e=>{const i=Number(e.target.dataset.a);e.target.checked?state.selected.add(i):state.selected.delete(i);renderQuestion()});document.querySelector('#home').onclick=home;if(state.checked)document.querySelector('#next').onclick=nextLearn;else document.querySelector('#check').onclick=checkLearn}
function tipHtml(q){if(!q.quickTip&&!q.sources?.length)return '';return `<div class="quicktip"><h3>💡 QuickTipp</h3>${q.quickTip?`<p>${q.quickTip}</p>`:''}${q.sources?.length?`<p class="source">📖 Nachlesen: ${q.sources.map(x=>`${x.document}${x.section?' · '+x.section:''}`).join(' · ')}</p>`:''}</div>`} function feedbackHtml(q){const correct=q.answers.map((a,i)=>a.correct?i:null).filter(i=>i!==null);const ok=sameSet([...state.selected],correct);return `<div class="feedback ${ok?'good':'bad'}">${ok?'✅ Richtig!':'🙂 Noch nicht ganz. Die richtigen Antworten sind grün markiert.'}</div>${tipHtml(q)}`}
function checkLearn(){const q=state.current;const correct=q.answers.map((a,i)=>a.correct?i:null).filter(i=>i!==null);const ok=sameSet([...state.selected],correct);const s=qStat(q.id);s.seen++;s.last=Date.now();if(ok){s.right++;s.streak++}else{s.wrong++;s.streak=0}stats.questions[q.id]=s;saveStats();state.checked=true;renderQuestion()}
function examSetup(){screen(`<section class="card exam-setup"><h2>🏁 Prüfung üben</h2><p>Während der Prüfung gibt es keine Auflösung. Erst am Ende siehst du dein Ergebnis.</p><label for="count">Wie viele Fragen?</label><select id="count">${[10,20,30].filter(n=>n<=db.questions.length).map(n=>`<option>${n}</option>`).join('')}</select><label for="mins">Wie viele Minuten?</label><select id="mins"><option>10</option><option selected>20</option><option>30</option></select><div class="actions"><button class="btn" id="real">🏁 Prüfungssimulation · 30 Fragen · 30 Minuten</button><button class="btn secondary" id="start">Eigene Prüfung starten</button><button class="btn ghost" id="back">Zurück</button></div></section>`);document.querySelector('#back').onclick=home;document.querySelector('#real').onclick=()=>startExam(30,30);document.querySelector('#start').onclick=()=>startExam(Number(document.querySelector('#count').value),Number(document.querySelector('#mins').value))}
function startExam(count,mins){state.exam={questions:shuffle(db.questions).slice(0,count),index:0,answers:{},end:Date.now()+mins*60000,timer:null};state.mode='exam';examQuestion();state.exam.timer=setInterval(()=>{if(!state.exam)return;const left=state.exam.end-Date.now();if(left<=0){clearInterval(state.exam.timer);finishExam();return}const e=document.querySelector('#timer');if(e){e.textContent=formatTime(left);if(left<120000)e.classList.add('warn')}},1000)}
function formatTime(ms){const s=Math.max(0,Math.ceil(ms/1000));return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}
function examQuestion(){const ex=state.exam,q=ex.questions[ex.index];state.current=q;const selected=new Set(ex.answers[q.id]||[]);const order=shuffle(q.answers.map((_,i)=>i));screen(`<section class="card"><div class="topbar"><span class="pill">Frage ${ex.index+1} von ${ex.questions.length}</span><span class="pill timer" id="timer">${formatTime(ex.end-Date.now())}</span></div><div class="progress"><span style="width:${((ex.index+1)/ex.questions.length)*100}%"></span></div><div class="question">${q.question}</div><p class="subtle">Eine oder mehrere Antworten können richtig sein.</p><div class="answers">${order.map(i=>`<label class="answer"><input type="checkbox" data-a="${i}" ${selected.has(i)?'checked':''}><span>${q.answers[i].text}</span></label>`).join('')}</div><div class="actions"><button class="btn" id="next">${ex.index===ex.questions.length-1?'Prüfung abgeben':'Weiter →'}</button>${ex.index>0?'<button class="btn secondary" id="prev">← Zurück</button>':''}</div></section>`);document.querySelectorAll('[data-a]').forEach(el=>el.onchange=()=>{const vals=[...document.querySelectorAll('[data-a]:checked')].map(x=>Number(x.dataset.a));ex.answers[q.id]=vals});document.querySelector('#next').onclick=()=>{if(ex.index===ex.questions.length-1)finishExam();else{ex.index++;examQuestion()}};const p=document.querySelector('#prev');if(p)p.onclick=()=>{ex.index--;examQuestion()}}
function finishExam(){const ex=state.exam;if(!ex)return;clearInterval(ex.timer);let right=0;const rows=ex.questions.map(q=>{const chosen=ex.answers[q.id]||[];const correct=q.answers.map((a,i)=>a.correct?i:null).filter(i=>i!==null);const ok=sameSet(chosen,correct);if(ok)right++;return{q,ok,chosen,correct}});state.exam=null;const pct=Math.round(right/rows.length*100);screen(`<section class="card hero"><div class="kart">${pct>=80?'🏆':'🏁'}</div><h2>Prüfung beendet</h2><div class="stats"><div class="stat"><strong>${right}/${rows.length}</strong>richtig</div><div class="stat"><strong>${pct}%</strong>Ergebnis</div></div></section><section class="card"><h3>Noch einmal anschauen</h3>${rows.filter(r=>!r.ok).length?rows.filter(r=>!r.ok).map(r=>`<div class="exam-review"><p><strong>${r.q.id}</strong> ${r.q.question}</p><p><strong>Richtig:</strong> ${r.correct.map(i=>r.q.answers[i].text).join(' · ')}</p>${tipHtml(r.q)}</div>`).join(''):'<p>Alle Fragen richtig – stark! 🎉</p>'}<div class="actions"><button class="btn" id="again">Neue Prüfung</button><button class="btn ghost" id="home">Startseite</button></div></section>`);document.querySelector('#again').onclick=examSetup;document.querySelector('#home').onclick=home}
function statsView(){const entries=db.questions.map(q=>({q,s:qStat(q.id)}));const seen=entries.filter(x=>x.s.seen>0);const right=seen.reduce((n,x)=>n+x.s.right,0),wrong=seen.reduce((n,x)=>n+x.s.wrong,0),attempts=right+wrong,pct=attempts?Math.round(right/attempts*100):0;const hard=entries.filter(x=>x.s.wrong>0).sort((a,b)=>(b.s.wrong-b.s.right)-(a.s.wrong-a.s.right)).slice(0,8);screen(`<section class="card"><h2>⭐ Mein Lernstand</h2><div class="stats"><div class="stat"><strong>${seen.length}</strong>Fragen gesehen</div><div class="stat"><strong>${right}</strong>richtig</div><div class="stat"><strong>${wrong}</strong>noch nicht</div><div class="stat"><strong>${pct}%</strong>Trefferquote</div></div></section><section class="card"><h3>Das üben wir noch</h3>${hard.length?hard.map(x=>`<p><strong>${x.q.id}</strong> ${x.q.question}</p>`).join(''):'<p>Noch keine schwierigen Fragen gespeichert.</p>'}<div class="actions"><button class="btn" id="hard">Schwierige Fragen üben</button><button class="btn ghost" id="reset">Lernstand zurücksetzen</button><button class="btn secondary" id="back">Zurück</button></div></section>`);document.querySelector('#hard').onclick=()=>startLearn('hard');document.querySelector('#back').onclick=home;document.querySelector('#reset').onclick=()=>{if(confirm('Lernstand wirklich zurücksetzen?')){stats={questions:{},sessions:0};saveStats();statsView()}}}
async function init(){try{const res=await fetch('data/questions.json');if(!res.ok)throw new Error('Fragen konnten nicht geladen werden');db=await res.json();home()}catch(err){screen(`<section class="card"><h2>Die Fragen konnten nicht geladen werden.</h2><p>${err.message}</p><p class="subtle">Starte die Seite über einen kleinen Webserver oder über GitHub Pages – nicht direkt als file://-Datei.</p></section>`)}}
init();
